-- STORM EVENT DATA
CREATE TABLE IF NOT EXISTS STORMEVENT_DETAILS(
  BEGIN_YEARMONTH INTEGER,
  BEGIN_DAY INTEGER,
  BEGIN_TIME INTEGER,
  END_YEARMONTH INTEGER,
  END_DAY INTEGER,
  END_TIME INTEGER,
  EPISODE_ID INTEGER NOT NULL,
  EVENT_ID INTEGER NOT NULL,
  STATE TEXT,
  STATE_FIPS INTEGER,
  YEAR INTEGER,
  MONTH_NAME TEXT,
  EVENT_TYPE TEXT,
  CZ_TYPE TEXT, -- JC - COUNTY/PARISH, Z - NWS PUBLIC FOREAST ZONE, M - MARINE
  CZ_FIPS TEXT,
  CZ_NAME TEXT,
  WFO TEXT, -- NWS FORECAST OFFICE'S AREA OF RESPONSABILITY
  BEGIN_DATE_TIME TEXT,
  CZ_TIMEZONE TEXT,
  END_DATE_TIME TEXT,
  INJURIES_DIRECT INTEGER,
  INJURIES_INDIRECT INTEGER,
  DEATHS_DIRECT INTEGER,
  DEATHS_INDIRECT INTEGER,
  DAMAGE_PROPERTY TEXT,
  DAMAGE_CROPS TEXT,
  SOURCE TEXT,
  MAGNITUDE REAL,
  MAGNITUDE_TYPE TEXT,
  FLOOD_CAUSE TEXT,
  CATEGORY TEXT,
  TOR_F_SCALE TEXT,
  TOR_LENGTH TEXT,
  TOR_WIDTH TEXT,
  TOR_OTHER_WFO TEXT,
  TOR_OTHER_CZ_STATE TEXT,
  TOR_OTHER_CZ_FIPS TEXT,
  TOR_OTHER_CZ_NAME TEXT,
  BEGIN_RANGE REAL,
  BEGIN_AZIMUTH TEXT,
  BEGIN_LOCATION TEXT,
  END_RANGE TEXT,
  END_AZIMUTH TEXT,
  END_LOCATION TEXT,
  BEGIN_LAT REAL,
  BEGIN_LON REAL,
  END_LAT REAL,
  END_LON REAL,
  EPISODE_NARRATIVE TEXT,
  EVENT_NARRATIVE TEXT,
  DATA_SOURCE
);


CREATE TABLE IF NOT EXISTS STORMEVENT_LOCATIONS(
  YEARMONTH INTEGER,
  EPISODE_ID INTEGER,
  EVENT_ID INTEGER,
  LOCATION_INDEX INTEGER,
  RANGE REAL,
  AZIMUTH TEXT,
  LOCATION TEXT,
  LATITUDE REAL,
  LONGITUDE REAL,
  LAT2 INTEGER,
  LON2 INTEGER
);


CREATE TABLE IF NOT EXISTS STORMEVENT_FATALITIES(
  FAT_YEARMONTH INTEGER,
  FAT_DAY INTEGER,
  FAT_TIME INTEGER,
  FATALITY_ID NUMBER,
  EVENT_ID NUMBER,
  FATALITY_TYPE TEXT,
  FATALITY_DATE TEXT,
  FATALITY_AGE TEXT,
  FATALITY_SEX TEXT,
  FATALITY_LOCATION TEXT,
  EVENT_YEARMONTH INTEGER
);
